version: "3.8"

services:
  # api:
  #   image: node
  #   depends_on: 
  #     - db
  #   user: node
  #   working_dir: /home/node/app/fade
  #   env_file: ./.env
  #   volumes:
  #     - ./:/home/node/app/fade
  #   ports:
  #     - 5000:5000
  #   command: bash -c "npm run server"
  #   # command: bash -c "npm install && npm run server"
  #   networks:
  #     - db-network
  
  # client:
  #   image: node
  #   depends_on: 
  #     - api
  #   user: node
  #   working_dir: /home/node/app/fade/client
  #   env_file: ./.env
  #   volumes:
  #     - ./client:/home/node/app/fade/client
  #   ports:
  #     - 5173:5173
  #   # command: bash -c "npm install && npm start"
  #   command: bash -c "npm start"
  
  db:
    image: postgres
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    env_file:
      - ./.env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5432:5432
    volumes:
      - ./:/home/node/app/fade
