services:
  api:
    image: node
    depends_on: 
      - db
    user: node
    working_dir: /home/node/app/fade
    env_file: ./.env
    volumes:
      - ./:/home/node/app/fade
    ports:
      - 5000:5000
    command: bash -c "npm install && npm run server"
    links:
      - db
  
  client:
    image: node
    depends_on: 
      - api
    user: node
    working_dir: /home/node/app/fade/client
    env_file: ./.env
    volumes:
      - ./client:/home/node/app/fade/client
    ports:
      - 5173:5173
    command: bash -c "npm install && npm start"
  
  db:
    image: mongo
    container_name: db
    restart: always
    ports:
      - 27017:27017

    
