export const GET_BARBERSHOPS_REQUEST = 'GET_BARBERSHOPS_REQUEST'
export const GET_BARBERSHOPS_SUCCESS = 'GET_BARBERSHOPS_SUCCESS'
export const GET_BARBERSHOPS_FAIL = 'GET_BARBERSHOPS_FAIL'

export const GET_BARBERSHOP_REQUEST = 'GET_BARBERSHOP_REQUEST'
export const GET_BARBERSHOP_SUCCESS = 'GET_BARBERSHOP_SUCCESS'
export const GET_BARBERSHOP_FAIL = 'GET_BARBERSHOP_FAIL'

export const GET_BARBERSHOP_BARBER_REQUEST = 'GET_BARBERSHOP_BARBER_REQUEST'
export const GET_BARBERSHOP_BARBER_SUCCESS = 'GET_BARBERSHOP_BARBER_SUCCESS'
export const GET_BARBERSHOP_BARBER_FAIL = 'GET_BARBERSHOP_BARBER_FAIL'

export const GET_BARBERS_APPOINTMENTS_REQUEST =
	'GET_BARBERS_APPOINTMENTS_REQUEST'
export const GET_BARBERS_APPOINTMENTS_SUCCESS =
	'GET_BARBERS_APPOINTMENTS_SUCCESS'
export const GET_BARBERS_APPOINTMENTS_FAIL = 'GET_BARBERS_APPOINTMENTS_FAIL'
