export const POST_APPOINTMENT_REQUEST = 'POST_APPOINTMENT_REQUEST'
export const POST_APPOINTMENT_SUCCESS = 'POST_APPOINTMENT_SUCCESS'
export const POST_APPOINTMENT_FAIL = 'POST_APPOINTMENT_FAIL'

export const GET_USER_AVAILABLE_APPOINTMENTS_REQUEST =
	'GET_USER_AVAILABLE_APPOINTMENTS_REQUEST'
export const GET_USER_AVAILABLE_APPOINTMENTS_SUCCESS =
	'GET_USER_AVAILABLE_APPOINTMENTS_SUCCESS'
export const GET_USER_AVAILABLE_APPOINTMENTS_FAIL =
	'GET_USER_AVAILABLE_APPOINTMENTS_FAIL'

export const GET_USER_BOOKED_APPOINTMENTS_REQUEST =
	'GET_USER_BOOKED_APPOINTMENTS_REQUEST'
export const GET_USER_BOOKED_APPOINTMENTS_SUCCESS =
	'GET_USER_BOOKED_APPOINTMENTS_SUCCESS'
export const GET_USER_BOOKED_APPOINTMENTS_FAIL =
	'GET_USER_BOOKED_APPOINTMENTS_FAIL'

export const GET_USER_COMPLETED_APPOINTMENTS_REQUEST =
	'GET_USER_COMPLETED_APPOINTMENTS_REQUEST'
export const GET_USER_COMPLETED_APPOINTMENTS_SUCCESS =
	'GET_USER_COMPLETED_APPOINTMENTS_SUCCESS'
export const GET_USER_COMPLETED_APPOINTMENTS_FAIL =
	'GET_USER_COMPLETED_APPOINTMENTS_FAIL'

export const DELETE_APPOINTMENT_SUCCESS = 'DELETE_APPOINTMENT_SUCCESS'
export const DELETE_APPOINTMENT_FAIL = 'DELETE_APPOINTMENT_FAIL'

export const COMPLETE_APPOINTMENT_SUCCESS = 'COMPLETE_APPOINTMENT_SUCCESS'
export const COMPLETE_APPOINTMENT_FAIL = 'COMPLETE_APPOINTMENT_FAIL'
